### ISSUE TITLE
命令运行报错

### ISSUE THREAD

**Issue by nwcdlabs** [iceflow/nwcd-mirror#1]
sudo mkdir -p /etc/docker 
sudo tee /etc/docker/daemon.json << EOF
{ "registry-mirrors": ["https://dockerhub.mirror.nwcdcdn.cn"] } 
EOF 
sudo systemctl daemon-reload 
sudo systemctl restart docker

**Comment by iceflow** [comment]
commit 289783581827ce2eefb6e31b63f2784f14383756 修复
